ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.twaptrap]
path = "out/TwapTrap.sol/TwapTrap.json" # Path to trap json file
response_contract = "0x70470Cb6eE285b3288A82Ff18b3bd2C7f21cFEdB" # Token address
response_function = "transferFrom(address,address,uint256)"
cooldown_period_blocks = 8
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2
private_trap = true
whitelist = ["0x4f5d846f51eB01eE6d85940e1100E14f28F896FD"] # Operator address
address = "0xf6522E37cE478E73d74a87c2412D5e35eB4e11C3"